### ISSUE TITLE
Docker Compose up not working

### ISSUE THREAD

**Issue by susmit** [ObserveRTC/full-stack-examples#5]
Tried locally running the repo. Seems to work fine, but is not able to update mongodb database. I found the following error in webrtcapp console.

```
ObserveRTC::WebsocketTransport Thu, 06 Oct 2022 02:35:48 GMT Closed by the observer, reason: Not valid or not supported schema version: 2.1.8
```

**Comment by balazskreith** [comment]
That's not MongoDB.
We released schema 2.1.8 last week together with the client-monitor-js sending data according to the new schema, but the observer is not yet ready to accept it. For now I fix the client-monitor version for the local full-stack and get back to you.

**Comment by susmit** [comment]
With schema version does it work? will try to fix locally.

**Comment by balazskreith** [comment]
it was working with 2.0.x, but I made a mistake by defining the schema version in client-monitor-js and sfu-monitor-js as ^2.0.1, and they automatically pulled the 2.1.x when they are installed in local-stack, which the old observer was not able to parse. 

So I merged the new [observer](https://github.com/ObserveRTC/observer/commit/c3175c65403427e4a2b45bce5f7435c06800ee43) able to parse schema until 2.1.9. The client-monitor and sfu-monitor are also using fixed version of 2.1.8 from now in their package.json.

Please verify if the full-stack-example works now without issue, if no please post the log, if yes please close the issue

**Comment by susmit** [comment]
Lemme do it.

**Comment by susmit** [comment]
issue still persist. Do i need to follow any special instructions apart from READme
```
bundle.js:2 ObserveRTC::WebsocketTransport Thu, 06 Oct 2022 11:43:12 GMT Closed by the observer, reason: Not valid or not supported schema version: 2.1.8
```

**Comment by balazskreith** [comment]
Can you delete the docker image of the observer and compile it again?
We still use `observer:1.0.0-beta`, that can be stucked in docker images and it does not see to repull it

**Comment by susmit** [comment]
My Bad, Works like charm.
